import type { Metadata } from "next";
import { PageHero } from "@/components/PageHero";
import { CalendarLink, Countdown } from "@/components/RushTools";
import { chapter, externalLinkProps } from "@/data/chapter";
import { getFaqs,getRushEvents } from "@/data/events";

const description=`Autumn 2026 recruitment for Kappa Theta Pi at ${chapter.university}.`;
export const metadata:Metadata={title:"Rush",description,openGraph:{title:`Rush · ${chapter.shortName}`,description,images:[chapter.socialImage]},twitter:{title:`Rush · ${chapter.shortName}`,description,images:[chapter.socialImage]}};

export default async function Rush(){const events=await getRushEvents(),faqs=await getFaqs();const applicationUrl=chapter.links.application??chapter.links.linktree;const interestUrl=chapter.links.interestForm??chapter.links.linktree;return <main id="main"><PageHero kicker="Autumn 2026 rush" title="Come as you are." accent="Leave with momentum." body="You don’t need a perfect résumé or years of coding. Bring curiosity, generosity, and a point of view."/><section className="deadline"><div className="wrap"><div><span>Applications close</span><strong>September 13 · 11:59 PM</strong></div><div><span>Time remaining</span><strong><Countdown/></strong></div><a className="button" href={applicationUrl} {...externalLinkProps} aria-label="Start application through the current KTP links (opens in new tab)">Start application</a></div></section><section className="section schedule"><div className="wrap"><div className="section-heading"><p className="eyebrow dark">Rush schedule</p><h2 className="display">Your week,<br/>at a glance.</h2></div><div className="schedule-list">{events.map((event,index)=>{const date=new Date(event.startsAt);return <article key={event.id}><div className="schedule-date"><strong>{date.toLocaleDateString("en-US",{timeZone:"America/New_York",weekday:"short"})}</strong><span>{date.toLocaleDateString("en-US",{timeZone:"America/New_York",month:"short",day:"numeric"})}</span><small>{date.toLocaleTimeString("en-US",{timeZone:"America/New_York",hour:"numeric",minute:"2-digit"})}</small></div><div><div className="event-meta"><span className={event.isOpen?"open":"invite"}>{event.isOpen?"Open to all":"Invite only"}</span><span>0{index+1}</span></div><h2>{event.title}</h2><strong>{event.location}</strong><p>{event.description}</p><CalendarLink event={event}/></div></article>})}</div></div></section><section className="faq-section section"><div className="wrap split"><div><p className="eyebrow">The honest answers</p><h2 className="display">Before you ask.</h2><p>Still have questions? Email <a href={chapter.links.email}>{chapter.email}</a> or message <a href={chapter.links.instagram} {...externalLinkProps} aria-label={`${chapter.handles.instagram} on Instagram (opens in new tab)`}>{chapter.handles.instagram}</a>.</p></div><div className="faqs">{faqs.map(f=><details key={f.id}><summary>{f.question}<span>+</span></summary><p>{f.answer}</p></details>)}</div></div></section><div className="mobile-rush-actions"><a href={interestUrl} {...externalLinkProps} aria-label="Interest form through Linktree (opens in new tab)">Interest form</a><a href={applicationUrl} {...externalLinkProps} aria-label="Application through Linktree (opens in new tab)">Apply now</a></div></main>}
