import type { Metadata } from "next";
import { ContactChannels } from "@/components/ContactChannels";
import { PageHero } from "@/components/PageHero";
import { chapter, externalLinkProps } from "@/data/chapter";

const description=`Get in touch with Kappa Theta Pi at ${chapter.university}.`;
export const metadata:Metadata={title:"Contact",description,openGraph:{title:`Contact · ${chapter.shortName}`,description,images:[chapter.socialImage]},twitter:{title:`Contact · ${chapter.shortName}`,description,images:[chapter.socialImage]}};

export default function Contact(){return <main id="main"><PageHero kicker="Get in touch" title="There’s room at" accent="the table." body="Questions about rush, partnerships, alumni connections, or chapter life? We’d like to hear from you."/><section className="section"><div className="wrap"><ContactChannels/><div className="contact-grid contact-lower"><div className="contact-details"><div><span>Campus organization resources</span><a href={chapter.links.studentActivities} {...externalLinkProps} aria-label={`${chapter.university} Student Activities (opens in new tab)`}>{chapter.university} Student Activities ↗</a></div></div><form className="contact-form" action={chapter.links.email} method="post" encType="text/plain"><label><span>Name</span><input required name="name" autoComplete="name"/></label><label><span>Email</span><input required type="email" name="email" autoComplete="email"/></label><label><span>I’m reaching out about</span><select name="topic"><option>Rush</option><option>Professional partnership</option><option>Alumni</option><option>General question</option></select></label><label><span>Message</span><textarea required name="message" rows={6}/></label><button className="button" type="submit">Open email draft</button><p>This form opens your email app; it doesn&apos;t store your information.</p></form></div></div></section></main>}
